title: Fred a.k.a Mastakod
logo: assets/images/fred.jpg
show_download: TRUE
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
